contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

baseurl = "/"
languageCode = "pt-br"
title = "Caio Almeida #dev"
theme = "beautifulhugo"
DisqusShortname = true

[indexes]
   category = "categories"

[Params]
  logo = "img/caiofralmeida.jpg"
  title = "my photo"
  subtitle = "Formado em Redes de computadores, desenvolvedor de software com foco em backend h√° mais de 4 anos, fascinado por tecnologia. Atualmente trabalha na Catho contribuindo para que diversas pessoas possam ter uma vida melhor."
  textOnLeftBar = "caioalmeida.eti.br"

[Author]
  name = "Caio Almeida"
  email = "caioamd@hotmail.com"
  facebook = "caio.fabio.almeida"
  github = "caiofralmeida"
  linkedin = "pub/caio-almeida/85/b55/388"
  stackoverflow = "6180793/caio-almeida"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
